name: Run Spring Boot Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres-test:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
          POSTGRES_DB: sonar
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U sonar"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
          

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U test; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Build & Run Tests
        run: mvn clean test -Dspring.profiles.active=ci

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml